/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./src/env.d.ts` (hash: 94e2139542e463a2c6aac799521ffd40)
interface __BaseEnv_Env {
	BUCKET: R2Bucket;
	CACHE_METRICS: AnalyticsEngineDataset;
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ACTIVE_RELEASE: "local-map-r1";
	EXPECTED_MANIFEST_SHA256: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
	CANONICAL_HOST: "localhost";
	DIRECT_TILE_ORIGIN: "https://tiles.fanmap42.com";
	READINESS_CACHE_SECONDS: "5";
	NEGATIVE_METADATA_CACHE_SECONDS: "5";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ACTIVE_RELEASE" | "EXPECTED_MANIFEST_SHA256" | "CANONICAL_HOST" | "DIRECT_TILE_ORIGIN" | "READINESS_CACHE_SECONDS" | "NEGATIVE_METADATA_CACHE_SECONDS">> {}
}
